<?php

use Custobar\CustoConnector\Block\Statistics\Config\Customer;
use Magento\Framework\Escaper;

/* @var Customer $block */
/* @var Escaper $escaper */
?>

<?php // Assumes cstbrConfig is defined in parent blocks --> ?>
<?php $customerId = $block->getCurrentCustomerId(); ?>
<?php if ($customerId > 0): ?>
    <script>
        cstbrConfig.customerId = "<?= $escaper->escapeHtml($customerId); ?>";
    </script>
<?php endif; ?>
