<?php

use Custobar\CustoConnector\Block\Statistics\GTM;
use Magento\Framework\Escaper;

/* @var GTM $block */
/* @var Escaper $escaper */
?>

<?php // cstbrConfig is filled up in child blocks ?>
<script>
    var cstbrConfig = {};
</script>
<?= $block->getChildHtml(); ?>

<?php $fieldMapping = $block->getFieldMapping(); ?>
<?php if ($fieldMapping): ?>
    <script>
        var gtmData = {};

        <?php // And here it's contents are put to object pushed to dataLayer, based on block configuration ?>
        <?php foreach ($fieldMapping as $gtmField => $configField): ?>
            if (cstbrConfig.hasOwnProperty('<?= $escaper->escapeJs($configField); ?>')) {
                gtmData.<?= $escaper->escapeJs($gtmField); ?> = cstbrConfig.<?= $escaper->escapeJs($configField); ?>;
            }
        <?php endforeach; ?>

        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push(gtmData);
    </script>
<?php endif; ?>
